apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapi-dep
  labels:
    app: myapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapi
  template:
    metadata:
      labels:
        app: myapi
    spec:
      containers:
      - name: myapi
        image: trenault828/testapp:latest
        ports:
        - containerPort: 80

