on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akstestregistrygenetec.azurecr.io
        username: ${{ secrets.acr_akstestregistrygenetec_username }}
        password: ${{ secrets.acr_akstestregistrygenetec_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/TestApp" -f  "TestApp/Dockerfile" -t akstestregistrygenetec.azurecr.io/akscluster:${{ github.sha }} --label dockerfile-path=TestApp/Dockerfile
        docker push akstestregistrygenetec.azurecr.io/akscluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_akscluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep akscluster85f0 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace akscluster85f0`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: akscluster85f0
        container-registry-url: akstestregistrygenetec.azurecr.io
        container-registry-username: ${{ secrets.acr_akstestregistrygenetec_username }}
        container-registry-password: ${{ secrets.acr_akstestregistrygenetec_password }}
        secret-name: aksclusterdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: akscluster85f0
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akstestregistrygenetec.azurecr.io/akscluster:${{ github.sha }}
        imagepullsecrets: |
          aksclusterdockerauth
